import './globals.css';
import Navbar from "@/components/layout/Navbar"
import { Comfortaa } from 'next/font/google';
import Evermore1 from 'next/font/local';
import Footer from '@/components/layout/Footer';
const evermore = Evermore1({ src: "../public/fonts/Evermore-normal.ttf",variable:"--font-evermore" });
const comfortaa = Comfortaa({ subsets: ['latin'],variable:"--font-comfortaa" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${evermore.variable} ${comfortaa.variable}`}>
        <div className="bg-bgcolor">
        <Navbar />
          {children}
        <Footer />
        </div>
      </body>
    </html>
  )
}
